# Generated by Django 4.1.1 on 2022-09-21 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=250, verbose_name='Listings')),
                ('listing_id', models.IntegerField(verbose_name='Listing ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Contact Date & Time')),
                ('user_id', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
