# Generated by Django 4.1.1 on 2022-09-14 00:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zipcode', models.CharField(max_length=50, verbose_name='ZipCode')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('bedrooms', models.IntegerField(verbose_name='Bedroom')),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Bathroom')),
                ('garage', models.IntegerField(default=0, verbose_name='Garage')),
                ('sqft', models.IntegerField(verbose_name='Sqft')),
                ('lot_size', models.FloatField(verbose_name='Lot Size')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Main Photo')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 1')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 2')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 3')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 4')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 5')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo 6')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('list_date', models.DateField(default=datetime.datetime.now, verbose_name='List Date')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor', verbose_name='Realtor')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
    ]
