# Generated by Django 4.1.1 on 2022-09-14 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('photo', models.ImageField(upload_to='photo/%Y%m%d/', verbose_name='Photo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('phone', models.CharField(max_length=50, verbose_name='Mobile Number')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('is_mvp', models.BooleanField(default=False, verbose_name='Is MVP')),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Hire Date')),
            ],
            options={
                'verbose_name': 'Realtor',
                'verbose_name_plural': 'Realtors',
            },
        ),
    ]
